spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tunkbook_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

# sql: first_name->mybatis: firstName
mybatis:
  configuration:
    map-underscore-to-camel-case: true