spring:
  # 设置视图层
#  mvc:
#    view:
#      prefix: "/WEB-INF/view"
#      suffix: "html"

  # configurar el perfil de desarrollo
  profiles:
    active: dev
  datasource:
    #mysql
    url: jdbc:mysql://localhost:3306/tunkbook_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

# configurar el puerto de localhost
server:
    port: 8080
#    servlet:
#      context-path: /spring-boot-mybatis

file:
  upload-path: D:/2333/Project_TunkBook_Backend/tunkbook-web/uploads/img/
# sql: first_name->mybatis: firstName
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/tunkbook/mapper/*.xml
  type-aliases-package: com.tunkbook.pojo

logging:
  level:
    root: info